import { PayloadType, PayloadVersion, DeviceRole, RequestType, ControlSubType } from './enums';

// Reference: https://github.com/meshcore-dev/MeshCore/blob/main/docs/payloads.md

export interface BasePayload {
  type: PayloadType;
  version: PayloadVersion;
  isValid: boolean;
  errors?: string[];
}

export interface AdvertPayload extends BasePayload {
  publicKey: string;
  timestamp: number;
  signature: string;
  signatureValid?: boolean; // Ed25519 signature verification result
  signatureError?: string; // Error message if verification failed
  appData: {
    flags: number;
    deviceRole: DeviceRole;
    hasLocation: boolean;
    hasName: boolean;
    location?: {
      latitude: number;
      longitude: number;
    };
    name?: string;
  };
}

export interface TracePayload extends BasePayload {
  traceTag: string;
  authCode: number;
  flags: number;
  pathHashes: string[];
  snrValues?: number[]; // from path field for TRACE packets
}

export interface GroupTextPayload extends BasePayload {
  channelHash: string;
  cipherMac: string;
  ciphertext: string; // raw encrypted data as hex
  ciphertextLength: number;
  decrypted?: {
    timestamp: number;
    flags: number;
    sender?: string;
    message: string;
    channelKey?: string;
  };
}

export interface RequestPayload extends BasePayload {
  destinationHash: string;
  sourceHash: string;
  cipherMac: string;
  ciphertext: string; // raw encrypted data as hex
  timestamp: number; // encrypted, set to 0 unless decrypted
  requestType: RequestType; // encrypted, default value unless decrypted
  requestData?: string; // encrypted, empty unless decrypted
  decrypted?: {
    timestamp: number;
    requestType: RequestType;
    requestData?: string;
  };
}

export interface TextMessagePayload extends BasePayload {
  destinationHash: string;
  sourceHash: string;
  cipherMac: string;
  ciphertext: string; // raw encrypted data as hex
  ciphertextLength: number;
  decrypted?: {
    timestamp: number;
    flags: number;
    attempt: number;
    message: string;
  };
}

export interface AnonRequestPayload extends BasePayload {
  destinationHash: string;
  senderPublicKey: string;
  cipherMac: string;
  ciphertext: string; // raw encrypted data as hex
  ciphertextLength: number;
  decrypted?: {
    timestamp: number;
    syncTimestamp?: number; // room server only
    password: string;
  };
}

export interface AckPayload extends BasePayload {
  checksum: string;
}

export interface PathPayload extends BasePayload {
  pathLength: number;
  pathHashes: string[];
  extraType: number;
  extraData: string;
}

export interface ResponsePayload extends BasePayload {
  destinationHash: string;
  sourceHash: string;
  cipherMac: string;
  ciphertext: string; // raw encrypted data as hex
  ciphertextLength: number;
  decrypted?: {
    tag: number;
    content: string;
  };
}

// Base interface for Control payloads
export interface ControlPayloadBase extends BasePayload {
  subType: ControlSubType;
  rawFlags: number; // full first byte with sub-type in upper 4 bits
}

// DISCOVER_REQ control packet payload
// Sent to discover nodes around you (zero-hop)
export interface ControlDiscoverReqPayload extends ControlPayloadBase {
  subType: ControlSubType.NodeDiscoverReq;
  prefixOnly: boolean; // lowest bit of flags byte
  typeFilter: number; // bit for each ADV_TYPE_*
  typeFilterNames: string[]; // human-readable list of filtered node types
  tag: number; // uint32, randomly generated by sender
  since: number; // uint32, optional epoch timestamp (0 if not present)
}

// DISCOVER_RESP control packet payload
// Response to DISCOVER_REQ containing node info
export interface ControlDiscoverRespPayload extends ControlPayloadBase {
  subType: ControlSubType.NodeDiscoverResp;
  nodeType: DeviceRole; // lower 4 bits of flags byte (matches ADV_TYPE_*)
  nodeTypeName: string; // human-readable node type
  snr: number; // signed int8 / 4 = dB, the inbound SNR
  tag: number; // uint32, reflected back from DISCOVER_REQ
  publicKey: string; // 8 or 32 bytes depending on prefix_only flag
  publicKeyLength: number; // 8 (prefix) or 32 (full)
}

// Union type for all Control payload sub-types
export type ControlPayload = ControlDiscoverReqPayload | ControlDiscoverRespPayload;

// union type for all payload types
export type PayloadData = 
  | AdvertPayload 
  | TracePayload 
  | GroupTextPayload 
  | RequestPayload 
  | TextMessagePayload 
  | AnonRequestPayload 
  | AckPayload 
  | PathPayload
  | ResponsePayload
  | ControlPayload;
